# 数组的创建和访问

In [ ]:
import numpy as np
"""
通过列表用array()和单独用arange()创建数组
常见的查看数组属性的操作，查看行列数、元素个数、类型等
创建特殊的矩阵，如０矩阵、单位矩阵以及任意行列数的矩阵方法
"""

In [2]:
# create from python list
list_1 = [1,2,3,4]

In [3]:
list_1

[1, 2, 3, 4]

In [4]:
array_1 = np.array(list_1)

In [5]:
array_1

array([1, 2, 3, 4])

In [6]:
list_2 = [5,6,7,8]

In [7]:
array_2 = np.array([list_1,list_2])

In [8]:
array_2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
# 获取数组属性
array_2.shape #几行几列

(2, 4)

In [10]:
array_2.size # 元素个数

8

In [11]:
array_2.dtype # 类型

dtype('int64')

In [12]:
array_3 = ([1,2,3],[1.4,2.1,3])

In [13]:
array_3.dtype

AttributeError: 'tuple' object has no attribute 'dtype'

In [14]:
array_3 = ([[1,2,3],[1.4,2.1,3]])

In [15]:
array_3.dtype  

AttributeError: 'list' object has no attribute 'dtype'

In [16]:
array_3 = np.array([[1,2,3],[1.1,2.2,3.3]])

In [17]:
array_3.dtype

dtype('float64')

In [18]:
# arange()创建数组
array_4 = np.arange(1,10,2)

In [19]:
array_4

array([1, 3, 5, 7, 9])

In [20]:
# 全零矩阵
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [22]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
np.eye(5).dtype

dtype('float64')

In [25]:
a = np.arange(1,10)

In [26]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a[1]
a[1:5]

array([2, 3, 4, 5])

In [28]:
a[1]

2

In [29]:
b = np.array([[1,2,3],[4,5,6]])

In [30]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
b[1,0]

4

In [32]:
b[1][0]

4

In [33]:
c = np.array([[1,2,3],[4,5,6],[7,8,9]])
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
c[:2,1:]

array([[2, 3],
       [5, 6]])