# 快速创建数组

In [1]:
import numpy as np

In [2]:
np.random.randn(10)

array([ 0.97153294, -0.13342711,  0.42273477,  0.78421228, -2.32146942,
       -0.48901995,  0.94912544, -2.18680184, -0.76018099, -0.65585531])

In [3]:
np.random.randint(10)

8

In [5]:
np.random.randint(10,size=20)

array([7, 9, 5, 3, 7, 5, 3, 2, 2, 0, 9, 1, 3, 3, 6, 7, 7, 7, 8, 4])

In [6]:
np.random.randint(10,size=20).reshape(4,5)

array([[2, 7, 5, 5, 1],
       [9, 6, 7, 7, 7],
       [3, 3, 8, 0, 1],
       [2, 7, 1, 0, 2]])

# 数组的运算

In [12]:
a = np.random.randint(10,size=20).reshape(4,5)
a

array([[8, 9, 4, 1, 2],
       [1, 0, 1, 5, 0],
       [0, 2, 8, 3, 2],
       [9, 7, 7, 4, 3]])

In [10]:
b = np.random.randint(10,size=20).reshape(4,5)
b

array([[8, 8, 5, 0, 5],
       [3, 4, 0, 1, 8],
       [5, 5, 2, 1, 2],
       [8, 2, 6, 1, 8]])

In [13]:
a + b

array([[16, 17,  9,  1,  7],
       [ 4,  4,  1,  6,  8],
       [ 5,  7, 10,  4,  4],
       [17,  9, 13,  5, 11]])

In [14]:
a - b

array([[ 0,  1, -1,  1, -3],
       [-2, -4,  1,  4, -8],
       [-5, -3,  6,  2,  0],
       [ 1,  5,  1,  3, -5]])

In [16]:
a/b  # 有０非法

/home/huangbo/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[1.        , 1.125     , 0.8       ,        inf, 0.4       ],
       [0.33333333, 0.        ,        inf, 5.        , 0.        ],
       [0.        , 0.4       , 4.        , 3.        , 1.        ],
       [1.125     , 3.5       , 1.16666667, 4.        , 0.375     ]])

# 创建矩阵

In [17]:
np.mat([[1,2,3],[4,5,6]]) 

matrix([[1, 2, 3],
        [4, 5, 6]])

In [18]:
a

array([[8, 9, 4, 1, 2],
       [1, 0, 1, 5, 0],
       [0, 2, 8, 3, 2],
       [9, 7, 7, 4, 3]])

In [21]:
A = np.mat(a)
A

matrix([[8, 9, 4, 1, 2],
        [1, 0, 1, 5, 0],
        [0, 2, 8, 3, 2],
        [9, 7, 7, 4, 3]])

In [22]:
# 矩阵的运算
B = np.mat(b)
B

matrix([[8, 8, 5, 0, 5],
        [3, 4, 0, 1, 8],
        [5, 5, 2, 1, 2],
        [8, 2, 6, 1, 8]])

In [23]:
A + B

matrix([[16, 17,  9,  1,  7],
        [ 4,  4,  1,  6,  8],
        [ 5,  7, 10,  4,  4],
        [17,  9, 13,  5, 11]])

In [24]:
A - B

matrix([[ 0,  1, -1,  1, -3],
        [-2, -4,  1,  4, -8],
        [-5, -3,  6,  2,  0],
        [ 1,  5,  1,  3, -5]])

In [28]:
# 矩阵的乘法运算
a1 = np.mat(np.random.randint(10,size=20).reshape(4,5))

In [29]:
b1 = np.mat(np.random.randint(10,size=20).reshape(5,4))

In [35]:
a1*b1

matrix([[ 55,  70,  74,  80],
        [ 74, 129, 161, 124],
        [ 64,  94, 122,  91],
        [ 86, 100, 115, 134]])

# Array常用函数

In [37]:
a = np.random.randint(10,size=20).reshape(4,5)

In [39]:
np.unique(a) # 返回数组中唯一的值

array([0, 1, 2, 3, 4, 5, 8, 9])

In [40]:
a

array([[5, 4, 4, 8, 1],
       [0, 2, 9, 3, 0],
       [2, 1, 4, 5, 9],
       [8, 3, 2, 8, 1]])

In [42]:
sum(a) # 求数组每一列的和

array([15, 10, 19, 24, 11])

In [43]:
sum(a[0]) #求某一行的和

22

In [45]:
sum(a[:,0])　＃　第０列的和

15

In [46]:
a.max()　# 数组中最大的值

9

In [54]:
max(a[:,1]) #　第一列最大的值

4