# 使用ｐickle序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
f = open('x.pkl','wb')

In [5]:
pickle.dump(x,f)  # 序列化到文件中去

In [7]:
!ls

Array.ipynb  ａrray的input和output.ipynb  x.pkl  数组与矩阵运算.ipynb


In [8]:
f = open('x.pkl','rb')

In [9]:
pickle.load(f) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.save('one_array',x)

In [11]:
!ls

Array.ipynb    ａrray的input和output.ipynb  数组与矩阵运算.ipynb
one_array.npy  x.pkl


In [12]:
np.load('one_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y = np.arange(20)

In [14]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
np.savez('two_array',a=x,b=y)

In [16]:
!ls

Array.ipynb    ａrray的input和output.ipynb  x.pkl
one_array.npy  two_array.npz		    数组与矩阵运算.ipynb


In [17]:
c = np.load('two_array.npz')

In [18]:
c['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
c['b']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])